name: Trigger auto deployment for container-app-vmm5ca3zt235c

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-vmm5ca3zt235c-AutoDeployTrigger-41a8cabe-4933-4b74-bbae-03ba5e3cf513.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPVMM5CA3ZT235C_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPVMM5CA3ZT235C_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPVMM5CA3ZT235C_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPVMM5CA3ZT235C_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPVMM5CA3ZT235C_REGISTRY_PASSWORD }}
          containerAppName: container-app-vmm5ca3zt235c
          resourceGroup: todonodejspgsqlgoogleauth9c219019
          imageToBuild: default/container-app-vmm5ca3zt235c:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


